name: build-and-deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  
env:
  GKE_CLUSTER: resume-cluster    # Add your cluster name here.
  GKE_ZONE: us-central1          # Add your cluster zone here.
  TIMESTAMP: latest

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      TIMESTAMP: ${{ steps.set-time.outputs.TIMESTAMP }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Current Date as Env Variable
        run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - id: set-time
        name: Set Output Timestamp
        run: echo "TIMESTAMP=${{ env.TIMESTAMP }}" >> "$GITHUB_OUTPUT"

      - name: Pass Timestamp to Deploy Stage
        id: pass-ts
        run: |
          echo "::set-output name=TIMESTAMP::$TIMESTAMP"

  build-push-website:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push web-service
        uses: docker/build-push-action@v5
        with:
          context: web-service
          platforms: linux/amd64
          push: true
          tags: eddisonso/eddison-resume:${{needs.setup.outputs.TIMESTAMP}}, eddisonso/eddison-resume:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build-push-website, setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - id: "auth"
        name: "authenticate with google cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
  
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
  
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: "resume-418606"
  
      - name: Deploy
        run: |-
          kubectl set image deployment/resume-website resume-website=eddisonso/eddison-resume:${{needs.setup.outputs.TIMESTAMP}}
